### ISSUE TITLE
`file-extension-in-import` does not work with scoped packages

### ISSUE THREAD

**Issue by ehmicky** [mysticatea/eslint-plugin-node#160]
Packages are skipped by `file-extension-in-import` (which is good). However `@scoped/packages` are not skipped.

`index.js`:

```js
import '@gulp-sourcemaps/map-sources'
```

`.eslintrc.yml`:

```yml
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins: [node]
rules:
  node/file-extension-in-import: 2
```

`package.json`:

```json
{
  "name": "eslint-plugin-node-bug",
  "version": "1.0.0",
  "license": "ISC",
  "devDependencies": {
    "@gulp-sourcemaps/map-sources": "^1.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-node": "^9.0.0"
  }
}
```

```bash
$ eslint index.js

/home/ehmicky/eslint-plugin-node-bug/index.js
  1:8  error  require file extension '.js'  node/file-extension-in-import

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```
