### ISSUE TITLE
import method calls are incorrectly marked as unsupported

### ISSUE THREAD

**Issue by LJNeon** [mysticatea/eslint-plugin-node#210]
**Environment**

 * **Package Versions:**
   * eslint v6.8.0
   * eslint-plugin-node v11.0.0
 * **Node Version:** v13.11.0
 * **npm Version:** v6.13.7
 * **Parser:** babel-eslint v10.1.0 (for import meta syntax)

**Configuration:**

<details>
<summary>.eslintrc.yml</summary>

```yml
extends: ["eslint:recommended", "plugin:node/recommended"]

rules: {
  # ...
}

parser: "babel-eslint"

parserOptions: {
  ecmaVersion: 2020,
  sourceType: "module"
}
```

</details>

`package.json` has both `"type": "module"` and `"engines": {"node": ">=13.11.0"}` set.

**Command used to run ESLint:** `eslint src --ext .js`

**What did you expect to happen?**
ESLint wouldn't error, as `import()` is supported syntax that I need to use.

**What actually happened?**
```bash
/home/user/project/src/index.js
  46:15  error  'import()' expressions are not supported yet  node/no-unsupported-features/es-syntax
  48:27  error  'import()' expressions are not supported yet  node/no-unsupported-features/es-syntax
  52:35  error  'import()' expressions are not supported yet  node/no-unsupported-features/es-syntax
  53:37  error  'import()' expressions are not supported yet  node/no-unsupported-features/es-syntax
```
I removed private info from the file path but that response is otherwise untouched.
