### ISSUE TITLE
Support for harmony flags?

### ISSUE THREAD

**Issue by SnappyCroissant** [mysticatea/eslint-plugin-node#61]
I'm not sure how you'd go about this because package.json doesn't have a way of marking harmony mode as required, and it may not be a big enough necesity to warrant the difficulty, particularly moving forward as node support for ES6/7 grows.

**Comment by dinoboff** [comment]
Right now you can use the "ignores" option of the "no-unsupported-features" rule:
```yaml
plugins:
  - node
extends:
  - plugin:node/recommended
env:
  node: true
  commonjs: true
  es6: true
parserOptions: 
  ecmaVersion: 2017
  sourceType: script
rules:
  node/no-unsupported-features:
    - error
    - version: 7
      ignores:
        - asyncAwait
```
